syntax = "proto3";

package trading;

import "google/protobuf/timestamp.proto";

service TradingService {
  rpc StreamEvents(stream StreamEventsRequest) returns (stream TradingEvent);
}

message StreamEventsRequest {
  oneof msg {
    Init init = 1;
    Subscribe subscribe = 2;
    Unsubscribe unsubscribe = 3;
    Heartbeat ping = 4;
  }
}

message Init {
  string account_id = 1;
}

message Subscribe {
  repeated EventType subscriptions = 2;
  string symbol = 3;
}

message Unsubscribe {
  repeated EventType subscriptions = 1;
  string symbol = 2;
}

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;
  EVENT_TYPE_BROKER_ORDER = 1;
  EVENT_TYPE_BROKER_POSITION = 2;
}

message TradingEvent {
  oneof event {
    Connected connected = 1;
    Received received = 2;
    Heartbeat heartbeat = 3;
    BrokerOrder broker_order = 4;
    BrokerPosition broker_position = 5;
  }
}

message Received {
  string message = 1;
  repeated string symbols = 2;
  repeated EventType subscriptions = 3;
}

message Connected {
  repeated EventType subscriptions = 1;
}

message Heartbeat {
  google.protobuf.Timestamp sent_at = 1;
}

//
// --------------------
// BROKER DATA
// --------------------
//

message BrokerOrder {
  string order_id = 1;
  string intent_id = 2;

  optional string external_order_id = 3;

  string account_id = 4;
  string broker = 5;
  string symbol = 6;

  string order_state = 7;
  string order_status = 8;

  string order_type = 9;
  string order_side = 10;

  optional Price limit_price = 11;
  optional Price average_price = 12;

  string route_strategy = 13;
  int64 quantity = 14;
  optional int64 filled_quantity = 15;

  string time_in_force = 16;

  google.protobuf.Timestamp received_at = 17;
  string organization_id = 18;
}

message BrokerPosition {
  string account_id = 1;
  string symbol = 2;
  int64 quantity = 3;
  Price average_cost = 4;
  google.protobuf.Timestamp received_at = 5;
  string organization_id = 6;
  string broker = 7;
}

message Price {
  int64 integer = 1;
  uint32 precision = 2;
}
