syntax = "proto3";

package trading;

import "google/protobuf/timestamp.proto";
import "trading/trading_types.proto";

message BrokerOrder {
  string order_id = 1;
  string intent_id = 2;

  optional string external_order_id = 3;

  string account_id = 4;
  Broker broker = 5;
  string symbol = 6;

  OrderState order_state = 7;
  OrderStatus order_status = 8;

  OrderType order_type = 9;
  OrderSide order_side = 10;

  optional string limit_price = 11;
  optional string stop_price = 12;
  optional string average_price = 13;

  RouteStrategy route_strategy = 14;

  string quantity = 15;
  string filled_quantity = 16;

  TimeInForce time_in_force = 17;

  google.protobuf.Timestamp received_at = 18;
  string organization_id = 19;
}

message BrokerPosition {
  string account_id = 1;
  string symbol = 2;
  string quantity = 3;
  string average_cost = 4;
  google.protobuf.Timestamp received_at = 5;
  string organization_id = 6;
  Broker broker = 7;
}
